import { Header } from "./components/Header";
import { Context } from "./context/store";
import "./globals.css";


export const metadata = {
  title: "Create App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body>
        <Header />
        <main className="h-screen flex-col">
          <Context>
            {children}
          </Context>
        </main>
      </body>


    </html>

  );
}
