import { Header } from "./components/Header";
import "./globals.css";


export const metadata = {
  title: "Create App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className="h-screen flex flex-col">
        <Header />
        <main className="flex-grow flex flex-col overflow-auto">
          {children}
        </main>
      </body>


    </html>

  );
}
